/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 C:\Users\amank\OneDrive\Desktop\music-app\frontend\metallica\public\drums.gltf 
Author: Vasian-Digital3D (https://sketchfab.com/Vasian-Digital3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/drum-kitantoni-f3a0a75485ea4482b417d58a521ac9c9
Title: Drum-kit+Antoni
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export default function Model(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/drums.gltf')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="2be4bcb9b7ba473eaf216aa9d442ec85fbx" rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Cylinder011" position={[2.458, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={30.646}>
                  <mesh name="Cylinder011_M_DrumKit_MainParts001_0" geometry={nodes.Cylinder011_M_DrumKit_MainParts001_0.geometry} material={materials['M_DrumKit_MainParts.001']} />
                  <mesh name="Cylinder011_M_DrumKit_MetalBits001_0" geometry={nodes.Cylinder011_M_DrumKit_MetalBits001_0.geometry} material={materials['M_DrumKit_MetalBits.001']} />
                </group>
                <group name="antony" position={[0.627, 2.721, 33.69]} rotation={[-Math.PI / 2, 0, 2.63]} scale={0.17}>
                  <group name="herotpp" position={[90.57, -100.715, -132.197]} rotation={[-1.886, -0.436, -0.246]}>
                    <group name="root" rotation={[0.001, 0, -1.57]}>
                      <group name="Object_10">
                        <group name="ik_foot_root" rotation={[0, -0.369, -0.001]}>
                          <group name="ik_foot_r" position={[28.641, -19.42, 0]} rotation={[-0.177, 0.119, -0.585]} />
                          <group name="ik_foot_l" position={[28.641, 19.42, 0]} rotation={[0.177, 0.119, 0.585]} />
                        </group>
                        <group name="ik_hand_root" rotation={[-0.005, -0.01, -0.461]}>
                          <group name="ik_hand_gun" position={[437.511, 0, 0]} rotation={[0, 0.011, 2.031]}>
                            <group name="ik_hand_l" position={[388.83, 0, 0]} />
                            <group name="ik_hand_r" />
                          </group>
                        </group>
                        <primitive object={nodes._rootJoint} />
                        <group name="Object_82" rotation={[-Math.PI / 2, 0, 0]} scale={10} />
                        <group name="Object_85" position={[21.444, 54.98, 4.359]} rotation={[0.834, 0.431, -2.854]} scale={0.046} />
                        <group name="Object_87" position={[-3.967, 38.214, -1.516]} rotation={[3.088, -0.095, 0.448]} scale={0.046} />
                        <skinnedMesh name="Object_83" geometry={nodes.Object_83.geometry} material={materials.Anton} skeleton={nodes.Object_83.skeleton} />
                        <skinnedMesh name="Object_84" geometry={nodes.Object_84.geometry} material={materials.material} skeleton={nodes.Object_84.skeleton} />
                        <skinnedMesh name="Object_86" geometry={nodes.Object_86.geometry} material={materials.palki} skeleton={nodes.Object_86.skeleton} />
                        <skinnedMesh name="Object_88" geometry={nodes.Object_88.geometry} material={materials.palki} skeleton={nodes.Object_88.skeleton} />
                      </group>
                    </group>
                  </group>
                </group>
                <group name="object01" position={[0.627, 2.721, 33.69]} rotation={[-Math.PI / 2, 0, 2.63]} scale={0.17} />
                <group name="1p" position={[21.444, 54.98, 4.359]} rotation={[0.834, 0.431, -2.854]} scale={0.046} />
                <group name="2p" position={[-3.967, 38.214, -1.516]} rotation={[3.088, -0.095, 0.448]} scale={0.046} />
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/drums.gltf')
