/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 keyboard.gltf 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/keyboard.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.chasis.geometry} material={materials['Material.001']} position={[0.138, -0.113, -0.986]} scale={0.05}>
        <group position={[-0.48, 0, -6.456]} rotation={[Math.PI / 2, 0, 0]} scale={6.106}>
          <group position={[1.867, 0.379, -0.11]}>
            <mesh geometry={nodes.key100.geometry} material={materials.Mat_2} position={[-4.221, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[1.958, 0.379, -0.11]}>
            <mesh geometry={nodes.key101.geometry} material={materials.Mat_2} position={[-4.312, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[1.995, 0.379, -0.111]}>
            <group position={[-4.288, 0.133, -0.067]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
              <lineSegments geometry={nodes.meshes3.geometry} material={materials.Material} />
              <mesh geometry={nodes.meshes3_1.geometry} material={materials.Material} />
            </group>
          </group>
          <group position={[2.049, 0.379, -0.11]}>
            <mesh geometry={nodes.key103.geometry} material={materials.Mat_2} position={[-4.403, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[2.096, 0.379, -0.111]}>
            <group position={[-4.379, 0.133, -0.067]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
              <lineSegments geometry={nodes.meshes5.geometry} material={materials.Material} />
              <mesh geometry={nodes.meshes5_1.geometry} material={materials.Material} />
            </group>
          </group>
          <group position={[2.14, 0.379, -0.11]}>
            <mesh geometry={nodes.key105.geometry} material={materials.Mat_2} position={[-4.494, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[2.198, 0.379, -0.111]}>
            <group position={[-4.47, 0.133, -0.067]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
              <lineSegments geometry={nodes.meshes7.geometry} material={materials.Material} />
              <mesh geometry={nodes.meshes7_1.geometry} material={materials.Material} />
            </group>
          </group>
          <group position={[2.232, 0.379, -0.11]}>
            <mesh geometry={nodes.key107.geometry} material={materials.Mat_2} position={[-4.585, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[2.323, 0.379, -0.11]}>
            <mesh geometry={nodes.key108.geometry} material={materials.Mat_2} position={[-4.676, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[-2.322, 0.383, -0.11]}>
            <mesh geometry={nodes.key21.geometry} material={materials.Mat_2} position={[-0.032, 0.047, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[-2.266, 0.379, -0.111]}>
            <group position={[-0.006, 0.133, -0.067]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
              <lineSegments geometry={nodes.meshes11.geometry} material={materials.Material} />
              <mesh geometry={nodes.meshes11_1.geometry} material={materials.Material} />
            </group>
          </group>
          <group position={[-2.231, 0.379, -0.11]}>
            <mesh geometry={nodes.key23.geometry} material={materials.Mat_2} position={[-0.123, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[-2.14, 0.379, -0.11]}>
            <mesh geometry={nodes.key24.geometry} material={materials.Mat_2} position={[-0.214, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[-2.101, 0.379, -0.111]}>
            <group position={[-0.188, 0.133, -0.067]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
              <lineSegments geometry={nodes.meshes14.geometry} material={materials.Material} />
              <mesh geometry={nodes.meshes14_1.geometry} material={materials.Material} />
            </group>
          </group>
          <group position={[-2.049, 0.379, -0.11]}>
            <mesh geometry={nodes.key26.geometry} material={materials.Mat_2} position={[-0.305, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[-2, 0.379, -0.111]}>
            <group position={[-0.279, 0.133, -0.067]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
              <lineSegments geometry={nodes.meshes16.geometry} material={materials.Material} />
              <mesh geometry={nodes.meshes16_1.geometry} material={materials.Material} />
            </group>
          </group>
          <group position={[-1.958, 0.379, -0.11]}>
            <mesh geometry={nodes.key28.geometry} material={materials.Mat_2} position={[-0.396, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[-1.867, 0.379, -0.11]}>
            <mesh geometry={nodes.key29.geometry} material={materials.Mat_2} position={[-0.487, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[-1.832, 0.379, -0.111]}>
            <group position={[-0.462, 0.133, -0.067]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
              <lineSegments geometry={nodes.meshes19.geometry} material={materials.Material} />
              <mesh geometry={nodes.meshes19_1.geometry} material={materials.Material} />
            </group>
          </group>
          <group position={[-1.775, 0.379, -0.11]}>
            <mesh geometry={nodes.key31.geometry} material={materials.Mat_2} position={[-0.578, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[-1.73, 0.379, -0.111]}>
            <group position={[-0.553, 0.133, -0.067]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
              <lineSegments geometry={nodes.meshes21.geometry} material={materials.Material} />
              <mesh geometry={nodes.meshes21_1.geometry} material={materials.Material} />
            </group>
          </group>
          <group position={[-1.684, 0.379, -0.11]}>
            <mesh geometry={nodes.key33.geometry} material={materials.Mat_2} position={[-0.669, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[-1.628, 0.379, -0.111]}>
            <group position={[-0.644, 0.133, -0.067]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
              <lineSegments geometry={nodes.meshes23.geometry} material={materials.Material} />
              <mesh geometry={nodes.meshes23_1.geometry} material={materials.Material} />
            </group>
          </group>
          <group position={[-1.593, 0.379, -0.11]}>
            <mesh geometry={nodes.key35.geometry} material={materials.Mat_2} position={[-0.76, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[-1.502, 0.379, -0.11]}>
            <mesh geometry={nodes.key36.geometry} material={materials.Mat_2} position={[-0.851, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[-1.463, 0.379, -0.111]}>
            <group position={[-0.826, 0.133, -0.067]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
              <lineSegments geometry={nodes.meshes26.geometry} material={materials.Material} />
              <mesh geometry={nodes.meshes26_1.geometry} material={materials.Material} />
            </group>
          </group>
          <group position={[-1.411, 0.379, -0.11]}>
            <mesh geometry={nodes.key38.geometry} material={materials.Mat_2} position={[-0.943, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[-1.362, 0.379, -0.111]}>
            <group position={[-0.917, 0.133, -0.067]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
              <lineSegments geometry={nodes.meshes28.geometry} material={materials.Material} />
              <mesh geometry={nodes.meshes28_1.geometry} material={materials.Material} />
            </group>
          </group>
          <group position={[-1.32, 0.379, -0.11]}>
            <mesh geometry={nodes.key40.geometry} material={materials.Mat_2} position={[-1.034, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[-1.229, 0.379, -0.11]}>
            <mesh geometry={nodes.key41.geometry} material={materials.Mat_2} position={[-1.125, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[-1.194, 0.379, -0.111]}>
            <group position={[-1.099, 0.133, -0.067]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
              <lineSegments geometry={nodes.meshes31.geometry} material={materials.Material} />
              <mesh geometry={nodes.meshes31_1.geometry} material={materials.Material} />
            </group>
          </group>
          <group position={[-1.138, 0.379, -0.11]}>
            <mesh geometry={nodes.key43.geometry} material={materials.Mat_2} position={[-1.216, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[-1.093, 0.379, -0.111]}>
            <group position={[-1.19, 0.133, -0.067]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
              <lineSegments geometry={nodes.meshes33.geometry} material={materials.Material} />
              <mesh geometry={nodes.meshes33_1.geometry} material={materials.Material} />
            </group>
          </group>
          <group position={[-1.047, 0.379, -0.11]}>
            <mesh geometry={nodes.key45.geometry} material={materials.Mat_2} position={[-1.307, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[-0.99, 0.379, -0.111]}>
            <group position={[-1.282, 0.133, -0.067]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
              <lineSegments geometry={nodes.meshes35.geometry} material={materials.Material} />
              <mesh geometry={nodes.meshes35_1.geometry} material={materials.Material} />
            </group>
          </group>
          <group position={[-0.956, 0.379, -0.11]}>
            <mesh geometry={nodes.key47.geometry} material={materials.Mat_2} position={[-1.398, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[-0.865, 0.379, -0.11]}>
            <mesh geometry={nodes.key48.geometry} material={materials.Mat_2} position={[-1.489, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[-0.826, 0.379, -0.111]}>
            <group position={[-1.464, 0.133, -0.067]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
              <lineSegments geometry={nodes.meshes38.geometry} material={materials.Material} />
              <mesh geometry={nodes.meshes38_1.geometry} material={materials.Material} />
            </group>
          </group>
          <group position={[-0.774, 0.379, -0.11]}>
            <mesh geometry={nodes.key50.geometry} material={materials.Mat_2} position={[-1.58, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[-0.724, 0.379, -0.111]}>
            <group position={[-1.555, 0.133, -0.067]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
              <lineSegments geometry={nodes.meshes40.geometry} material={materials.Material} />
              <mesh geometry={nodes.meshes40_1.geometry} material={materials.Material} />
            </group>
          </group>
          <group position={[-0.683, 0.379, -0.11]}>
            <mesh geometry={nodes.key52.geometry} material={materials.Mat_2} position={[-1.671, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[-0.592, 0.379, -0.11]}>
            <mesh geometry={nodes.key53.geometry} material={materials.Mat_2} position={[-1.762, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[-0.556, 0.379, -0.111]}>
            <group position={[-1.737, 0.133, -0.067]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
              <lineSegments geometry={nodes.meshes43.geometry} material={materials.Material} />
              <mesh geometry={nodes.meshes43_1.geometry} material={materials.Material} />
            </group>
          </group>
          <group position={[-0.5, 0.379, -0.11]}>
            <mesh geometry={nodes.key55.geometry} material={materials.Mat_2} position={[-1.853, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[-0.455, 0.379, -0.111]}>
            <group position={[-1.828, 0.133, -0.067]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
              <lineSegments geometry={nodes.meshes45.geometry} material={materials.Material} />
              <mesh geometry={nodes.meshes45_1.geometry} material={materials.Material} />
            </group>
          </group>
          <group position={[-0.409, 0.379, -0.11]}>
            <mesh geometry={nodes.key57.geometry} material={materials.Mat_2} position={[-1.944, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[-0.353, 0.379, -0.111]}>
            <group position={[-1.919, 0.133, -0.067]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
              <lineSegments geometry={nodes.meshes47.geometry} material={materials.Material} />
              <mesh geometry={nodes.meshes47_1.geometry} material={materials.Material} />
            </group>
          </group>
          <group position={[-0.318, 0.379, -0.11]}>
            <mesh geometry={nodes.key59.geometry} material={materials.Mat_2} position={[-2.035, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[-0.227, 0.379, -0.11]}>
            <mesh geometry={nodes.key60.geometry} material={materials.Mat_2} position={[-2.126, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[-0.188, 0.379, -0.111]}>
            <group position={[-2.101, 0.133, -0.067]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
              <lineSegments geometry={nodes.meshes50.geometry} material={materials.Material} />
              <mesh geometry={nodes.meshes50_1.geometry} material={materials.Material} />
            </group>
          </group>
          <group position={[-0.136, 0.379, -0.11]}>
            <mesh geometry={nodes.key62.geometry} material={materials.Mat_2} position={[-2.217, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[-0.087, 0.379, -0.111]}>
            <group position={[-2.193, 0.133, -0.067]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
              <lineSegments geometry={nodes.meshes52.geometry} material={materials.Material} />
              <mesh geometry={nodes.meshes52_1.geometry} material={materials.Material} />
            </group>
          </group>
          <group position={[-0.045, 0.379, -0.11]}>
            <mesh geometry={nodes.key64.geometry} material={materials.Mat_2} position={[-2.309, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[0.046, 0.379, -0.11]}>
            <mesh geometry={nodes.key65.geometry} material={materials.Mat_2} position={[-2.4, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[0.082, 0.379, -0.111]}>
            <group position={[-2.375, 0.133, -0.067]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
              <lineSegments geometry={nodes.meshes55.geometry} material={materials.Material} />
              <mesh geometry={nodes.meshes55_1.geometry} material={materials.Material} />
            </group>
          </group>
          <group position={[0.137, 0.379, -0.11]}>
            <mesh geometry={nodes.key67.geometry} material={materials.Mat_2} position={[-2.491, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[0.183, 0.379, -0.111]}>
            <group position={[-2.466, 0.133, -0.067]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
              <lineSegments geometry={nodes.meshes57.geometry} material={materials.Material} />
              <mesh geometry={nodes.meshes57_1.geometry} material={materials.Material} />
            </group>
          </group>
          <group position={[0.228, 0.379, -0.11]}>
            <mesh geometry={nodes.key69.geometry} material={materials.Mat_2} position={[-2.582, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[0.285, 0.379, -0.111]}>
            <group position={[-2.557, 0.133, -0.067]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
              <lineSegments geometry={nodes.meshes59.geometry} material={materials.Material} />
              <mesh geometry={nodes.meshes59_1.geometry} material={materials.Material} />
            </group>
          </group>
          <group position={[0.319, 0.379, -0.11]}>
            <mesh geometry={nodes.key71.geometry} material={materials.Mat_2} position={[-2.673, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[0.41, 0.379, -0.11]}>
            <mesh geometry={nodes.key72.geometry} material={materials.Mat_2} position={[-2.764, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[0.45, 0.379, -0.111]}>
            <group position={[-2.739, 0.133, -0.067]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
              <lineSegments geometry={nodes.meshes62.geometry} material={materials.Material} />
              <mesh geometry={nodes.meshes62_1.geometry} material={materials.Material} />
            </group>
          </group>
          <group position={[0.501, 0.379, -0.11]}>
            <mesh geometry={nodes.key74.geometry} material={materials.Mat_2} position={[-2.855, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[0.551, 0.379, -0.111]}>
            <group position={[-2.83, 0.133, -0.067]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
              <lineSegments geometry={nodes.meshes64.geometry} material={materials.Material} />
              <mesh geometry={nodes.meshes64_1.geometry} material={materials.Material} />
            </group>
          </group>
          <group position={[0.592, 0.379, -0.11]}>
            <mesh geometry={nodes.key76.geometry} material={materials.Mat_2} position={[-2.946, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[0.683, 0.379, -0.11]}>
            <mesh geometry={nodes.key77.geometry} material={materials.Mat_2} position={[-3.037, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[0.719, 0.379, -0.111]}>
            <group position={[-3.012, 0.133, -0.067]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
              <lineSegments geometry={nodes.meshes67.geometry} material={materials.Material} />
              <mesh geometry={nodes.meshes67_1.geometry} material={materials.Material} />
            </group>
          </group>
          <group position={[0.774, 0.379, -0.11]}>
            <mesh geometry={nodes.key79.geometry} material={materials.Mat_2} position={[-3.128, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[0.821, 0.379, -0.111]}>
            <group position={[-3.104, 0.133, -0.067]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
              <lineSegments geometry={nodes.meshes69.geometry} material={materials.Material} />
              <mesh geometry={nodes.meshes69_1.geometry} material={materials.Material} />
            </group>
          </group>
          <group position={[0.866, 0.379, -0.11]}>
            <mesh geometry={nodes.key81.geometry} material={materials.Mat_2} position={[-3.219, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[0.923, 0.379, -0.111]}>
            <group position={[-3.195, 0.133, -0.067]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
              <lineSegments geometry={nodes.meshes71.geometry} material={materials.Material} />
              <mesh geometry={nodes.meshes71_1.geometry} material={materials.Material} />
            </group>
          </group>
          <group position={[0.957, 0.379, -0.11]}>
            <mesh geometry={nodes.key83.geometry} material={materials.Mat_2} position={[-3.31, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[1.048, 0.379, -0.11]}>
            <mesh geometry={nodes.key84.geometry} material={materials.Mat_2} position={[-3.401, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[1.087, 0.379, -0.111]}>
            <group position={[-3.377, 0.133, -0.067]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
              <lineSegments geometry={nodes.meshes74.geometry} material={materials.Material} />
              <mesh geometry={nodes.meshes74_1.geometry} material={materials.Material} />
            </group>
          </group>
          <group position={[1.139, 0.379, -0.11]}>
            <mesh geometry={nodes.key86.geometry} material={materials.Mat_2} position={[-3.492, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[1.189, 0.379, -0.111]}>
            <group position={[-3.468, 0.133, -0.067]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
              <lineSegments geometry={nodes.meshes76.geometry} material={materials.Material} />
              <mesh geometry={nodes.meshes76_1.geometry} material={materials.Material} />
            </group>
          </group>
          <group position={[1.23, 0.379, -0.11]}>
            <mesh geometry={nodes.key88.geometry} material={materials.Mat_2} position={[-3.583, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[1.321, 0.379, -0.11]}>
            <mesh geometry={nodes.key89.geometry} material={materials.Mat_2} position={[-3.675, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[1.357, 0.379, -0.111]}>
            <group position={[-3.65, 0.133, -0.067]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
              <lineSegments geometry={nodes.meshes79.geometry} material={materials.Material} />
              <mesh geometry={nodes.meshes79_1.geometry} material={materials.Material} />
            </group>
          </group>
          <group position={[1.412, 0.379, -0.11]}>
            <mesh geometry={nodes.key91.geometry} material={materials.Mat_2} position={[-3.766, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[1.458, 0.379, -0.111]}>
            <group position={[-3.741, 0.133, -0.067]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
              <lineSegments geometry={nodes.meshes81.geometry} material={materials.Material} />
              <mesh geometry={nodes.meshes81_1.geometry} material={materials.Material} />
            </group>
          </group>
          <group position={[1.503, 0.379, -0.11]}>
            <mesh geometry={nodes.key93.geometry} material={materials.Mat_2} position={[-3.857, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[1.561, 0.379, -0.111]}>
            <group position={[-3.832, 0.133, -0.067]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
              <lineSegments geometry={nodes.meshes83.geometry} material={materials.Material} />
              <mesh geometry={nodes.meshes83_1.geometry} material={materials.Material} />
            </group>
          </group>
          <group position={[1.594, 0.379, -0.11]}>
            <mesh geometry={nodes.key95.geometry} material={materials.Mat_2} position={[-3.948, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[1.685, 0.379, -0.11]}>
            <mesh geometry={nodes.key96.geometry} material={materials.Mat_2} position={[-4.039, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[1.725, 0.379, -0.111]}>
            <group position={[-4.015, 0.133, -0.067]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
              <lineSegments geometry={nodes.meshes86.geometry} material={materials.Material} />
              <mesh geometry={nodes.meshes86_1.geometry} material={materials.Material} />
            </group>
          </group>
          <group position={[1.776, 0.379, -0.11]}>
            <mesh geometry={nodes.key98.geometry} material={materials.Mat_2} position={[-4.13, 0.051, -0.065]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038} />
          </group>
          <group position={[1.826, 0.379, -0.111]}>
            <group position={[-4.106, 0.133, -0.067]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
              <lineSegments geometry={nodes.meshes88.geometry} material={materials.Material} />
              <mesh geometry={nodes.meshes88_1.geometry} material={materials.Material} />
            </group>
          </group>
        </group>
      </mesh>
    </group>
  )
}

useGLTF.preload('/keyboard.gltf')
